version: '3.9'

services:
  gateway:
    image: bargain-dev
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - bargain
    volumes:
      - ./:/usr/app/apps/gateway
    command: yarn nx run gateway:serve

networks:
  bargain:
    external: true
