version: '3.9'

services:
  customer-portal:
    image: bargain-dev
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - bargain
    volumes:
      - ./:/usr/app/apps/customer-portal
    command: yarn nx run customer-portal:serve

networks:
  bargain:
    external: true
